
server:
  port: 5352
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/CoffeeWorld
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        type: trace
        jdbc.lob.non_contextual_creation: true
